package com.flowpilot.app.actions

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import com.flowpilot.app.data.model.ActionType
import java.io.File

/** Plays cached offline TTS audio generated by FlowPilot. */
class TtsExecutor(
    context: Context,
    private val ttsManager: TtsManager = TtsManager(context),
    private val playFile: ((File) -> Boolean)? = null,
) : ActionExecutor {
    private var activePlayer: MediaPlayer? = null

    override val supportedTypes = setOf(ActionType.SPEAK_TEXT)

    private fun play(file: File): Boolean {
        stopPreview()

        val player = MediaPlayer().apply {
            setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ASSISTANCE_ACCESSIBILITY).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build())
            setDataSource(file.absolutePath)
            setOnCompletionListener { completed ->
                if (activePlayer === completed) {
                    activePlayer = null
                }
                completed.release()
            }
            setOnErrorListener { failed, _, _ ->
                if (activePlayer === failed) {
                    activePlayer = null
                }
                failed.release()
                true
            }
            prepare()
            start()
        }
        activePlayer = player
        return player.isPlaying
    }

    override fun execute(action: ActionType, parameters: ActionParameters): ActionResult {
        if (action != ActionType.SPEAK_TEXT) return ActionResult(false, "Unsupported action for TTS")
        val fileName = parameters.ttsAudioFileName
        if (fileName.isBlank()) {
            return ActionResult(false, "TTS audio cache missing or not generated")
        }
        val file = ttsManager.getCacheFile(fileName)
            ?: return ActionResult(false, "TTS cache filename is invalid or unsafe: $fileName")
        if (!file.exists() || file.length() == 0L) {
            return ActionResult(false, "TTS cached audio file is missing or empty")
        }

        return try {
            if ((playFile ?: ::play)(file)) {
                ActionResult(true, "TTS audio played from offline cache")
            } else {
                ActionResult(false, "TTS audio playback failed")
            }
        } catch (t: Throwable) {
            ActionResult(false, t.message ?: t.javaClass.simpleName)
        }
    }

    fun playCacheFile(file: File): Boolean {
        val cacheFile = ttsManager.getCacheFile(file.name) ?: return false
        if (cacheFile.canonicalFile != file.canonicalFile || !cacheFile.isFile || cacheFile.length() <= 0L) return false
        return (playFile ?: ::play)(cacheFile)
    }

    fun stopPreview() {
        val player = activePlayer ?: return
        activePlayer = null
        try {
            if (player.isPlaying) player.stop()
        } catch (_: IllegalStateException) {
        } finally {
            player.release()
        }
    }
}
